Centric.Internship/Centric.Internship.Mvc/Entities/Event.cs
using System;

namespace Centric.Internship.Mvc.Entities
{
    public class Event
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public string Website { get; set; }
        public string ContactEmail { get; set; }
        public DateTime Date { get; set; }
    }
}

Centric.Internship/Centric.Internship.Mvc/Entities/User.cs
namespace Centric.Internship.Mvc.Storage
{
    public class User
    {
        public string Name { get; internal set; }
        public string Login { get; internal set; }
        public string Password { get; internal set; }
        public string Role { get; internal set; }
    }
}

Centric.Internship/Centric.Internship.Mvc/Models/EventModel.cs
using Centric.Internship.Mvc.Custom;
using Microsoft.AspNetCore.Mvc;
using System;
using System.ComponentModel.DataAnnotations;

namespace Centric.Internship.Mvc.Models
{
    public class EventModel
    {
        private DateTime _createdOn = DateTime.MinValue;

        [BindProperty] public Guid Id { get; set; }

        [BindProperty]
        [Required(ErrorMessage = "Name is required.")]
        [StringLength(1000)]
        [MinLength(10)]
        public string Name { get; set; }

        [Required(ErrorMessage = "Location is required.")]
        [StringLength(1000)]
        [MinLength(10)]
        public string Location { get; set; }

        [Required(ErrorMessage = "Description is required.")]
        [StringLength(1000)]
        [MinLength(10)]
        public string Description { get; set; }

        [Required(ErrorMessage = "Email address is required.")]
        [EmailSpecification]
        [EmailAddress(ErrorMessage = "Email address does not have a correct format.")]
        public string ContactEmail { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        public DateTime Date
        {
            get { return (_createdOn == DateTime.MinValue) ? DateTime.Now : _createdOn; }

            set { _createdOn = value; }
        }
    }
}

Centric.Internship/Centric.Internship.Mvc/Controllers/AccountController.cs
using System.Linq;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Centric.Internship.Mvc.Storage;

namespace Centric.Internship.Mvc.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(string userName, string password)
        {
            if (!string.IsNullOrEmpty(userName) && string.IsNullOrEmpty(password))
            {
                return RedirectToAction("Login");
            }

            //Check the user name and password  
            //Here can be implemented checking logic from the database  

            var user = UserStorage.Users.FirstOrDefault(x => x.Login == userName && x.Password == password);

            if (user != null)
            {
                var identity = new ClaimsIdentity(new[]
                {
                    new Claim(ClaimTypes.Name, userName),
                    new Claim(ClaimTypes.Role, user.Role)
                }, CookieAuthenticationDefaults.AuthenticationScheme);

                var principal = new ClaimsPrincipal(identity);

                var login = HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpGet]
        public ActionResult Logout()
        {
            var login = HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login");
        }
    }
}

Centric.Internship/Centric.Internship.Mvc/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Centric.Internship.Mvc.Entities;
using Centric.Internship.Mvc.Models;
using Centric.Internship.Mvc.Storage;
using Microsoft.AspNetCore.Mvc;

namespace Centric.Internship.Mvc.Controllers
{

    [Route("event/")]
    public class EventController : Controller
    {
        [Route("index")]
        //[Authorize(Roles = "admin")]
        public ActionResult<IEnumerable<EventModel>> Index()
        {
            ViewData["NextEventName"] = EventStorage.Events.OrderBy(e => e.Date).ElementAt(0).Name;
            var events = EventStorage.Events.Select(eventEntity => new EventModel
            {
                Name = eventEntity.Name,
                Location = eventEntity.Location,
                Description = eventEntity.Description,
                Date = eventEntity.Date,
                Id = eventEntity.Id
            });
            return View(events.ToList());
        }

        [HttpGet("details/{id}")]
        ////[CustomActionFilter]
        public IActionResult Details([FromRoute]Guid id)
        {
            var eventEntity = EventStorage.Events.FirstOrDefault(e => e.Id == id);
            if (eventEntity == null)
            {
                throw new Exception("Event not found");
            }
            return View(new EventModel
            {
                Name = eventEntity.Name,
                Location = eventEntity.Location,
                Description = eventEntity.Description,
                ContactEmail = eventEntity.ContactEmail,
                Date = eventEntity.Date
            });
        }

        [HttpGet("create")]
        public ActionResult Create()
        {
            return View("Create");
        }

        [HttpPost("create")]
        public ActionResult Create([FromForm] EventModel fromBody)
        {
            if (ModelState.IsValid)
            {
                EventStorage.AddEvent(new Event
                {
                    Id = Guid.NewGuid(),
                    Name = fromBody.Name,
                    Location = fromBody.Location,
                    Description = fromBody.Description,
                    ContactEmail = fromBody.ContactEmail,
                    Date = Convert.ToDateTime(fromBody.Date)
                });
            }
            else
            {
                return View("Create", fromBody);
            }
            
            return RedirectToAction("Index");
        }
    }
}

Centric.Internship/Centric.Internship.Mvc/Controllers/HomeController.cs
using System;
using Centric.Internship.Mvc.Custom;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Centric.Internship.Mvc.Controllers
{
    [Authorize]
    [Route("home/")]
    [CacheResource]
    public class HomeController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            ViewData["CachedMessage"] = "This is some cached content: " + DateTime.Now;
            return View();
        }
    }
}

Centric.Internship/Centric.Internship.Mvc/Views/Event/Create.cshtml
@model EventModel

@Html.ValidationSummary(true)
<section class="content container-fluid">
    <!-- Horizontal Form -->
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Add Event</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form class="form-horizontal" action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="box-body">
                <div class="form-group">
                    <label for="Name" class="control-label">Name</label>
                    <div class="col-sm-10">
                        <input asp-for="Name" name="Name" class="form-control"/>
                    </div>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="Location" class="control-label">Location</label>
                    <div class="col-sm-10">
                        <input asp-for="Location" name="Location" class="form-control"/>
                    </div>
                    <span asp-validation-for="Location" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="Description" class="control-label">Description</label>
                    <div class="col-sm-10">
                        <input asp-for="Description" name="Description" class="form-control"/>
                    </div>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="ContactEmail" class="control-label">Contact email</label>
                    <div class="col-sm-10">
                        <input asp-for="ContactEmail" name="ContactEmail" class="form-control"/>
                    </div>
                    <span asp-validation-for="ContactEmail" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="Date" class="control-label">Date</label>
                    <div class="col-sm-10">
                        <input type="date" asp-for="Date"  name="Date" class="form-control"/>
                    </div>
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-info pull-right">Create</button>
                <button type="reset" class="btn btn-info pull-right">Cancel</button>
            </div>
        </form>
    </div>
</section>

<div>
    <div>
        <p>@Html.ActionLink("Back to events list", "Index", "Event", new object { }, new object { })</p>
    </div>
</div>

Centric.Internship/Centric.Internship.Mvc/Views/Event/Details.cshtml
@model Centric.Internship.Mvc.Models.EventModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    var eventName = $"{Model.Name}";
}

@{
    var eventDetails = $" - {Model.Location} - {Model.Date}!";
}

<p><b>@eventName</b>@eventDetails</p>
<p>Description: @Model.Description</p>
<p>Contact details: @Model.ContactEmail</p>
<p>@Html.Raw(eventDetails)</p>

<p>
    @if (Model.Location.Contains("Centric"))
    {
        @:It is a company related event!
    }
    else
    {
        @:It is NOT in a company related event!
    }
</p>

Centric.Internship/Centric.Internship.Mvc/Views/Event/Index.cshtml
@model IList<Centric.Internship.Mvc.Models.EventModel>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@await Html.PartialAsync("_NextEvent")
<div>
    <p>@Html.ActionLink("Create new event", "Create", "Event", new object { }, new { @class = "btn btn-info" })</p>
</div>

<table class="table table-bordered table-hover">
    <tr>
        <th>Date</th>
        <th>Name</th>
        <th>Location</th>
        <th>Details</th>
    </tr>
    @foreach (var @eventModel in @Model)
    {
        <tr>
            <td>@eventModel.Date</td>
            <td>@eventModel.Name</td>
            <td>@eventModel.Location</td>
            <td>@Html.ActionLink("See more..", "Details", "Event", new { id = @eventModel.Id }, new { @class = "btn btn-info" })</td>
        </tr>
    }
</table>

Centric.Internship/Centric.Internship.Mvc/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var cachedData = ViewData["CachedMessage"] as string;
}

This is an app used for displaying events!

<p>@cachedData</p>

Centric.Internship/Centric.Internship.Mvc/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_Layout</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    </environment>

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">Internship.MVC</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Event" asp-action="Index">Events</a>
                    </li>
                </ul>
            </div>
            <div>
                <a class="nav-link" asp-controller="Account" asp-action="Logout">
                    Logout
                </a>
            </div>
        </nav>
    </header>

    <div class="my-app-container">
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/jquery-3.4.1.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/jquery-3.4.1.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    </environment>

    <footer class="footer">Centric Internship MVC</footer>
    @RenderSection("Scripts", required: false)
</body>
</html>

Centric.Internship/Centric.Internship.Mvc/Views/Shared/_NextEvent.cshtml
<p>Today is @DateTime.Now.ToString(), 
    next event is @ViewData["NextEventName"]</p>